<?php

namespace App\Models\Eloquent;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Log;

class BaseModel extends Model
{
    use HasFactory;

    public function delete()
    {
        Log::channel('activity')->info('Deleted', ['id' => auth()->user()->ID,'user' => auth()->user()->KULLANICIADI,'data' => $this]);
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
